# Generated by Django 2.2.5 on 2021-08-15 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reconBreed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='name',
        ),
    ]
